apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytcsapp20
  labels:
    app: mytcsapp20
  namespace: namespace-workflow-1698682582778
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytcsapp20
  template:
    metadata:
      labels:
        app: mytcsapp20
    spec:
      containers:
        - name: mytcsapp20
          image: acrworkflow1698682582778.azurecr.io/image-workflow-1698682582778:latest
          ports:
            - containerPort: 5000