apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapp
  labels:
    app: firstapp
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719763608005
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstapp
  template:
    metadata:
      labels:
        app: firstapp
    spec:
      containers:
        - name: firstapp
          image: acrworkflow1719763608005.azurecr.io/image-workflow-1719763608005:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
