apiVersion: v1
kind: Service
metadata:
  name: mytcsapp20
  namespace: namespace-workflow-1698682582778
spec:
  type: LoadBalancer
  selector:
    app: mytcsapp20
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000