apiVersion: v1
kind: Service
metadata:
  name: mytcsapp1
  namespace: namespace-workflow-1698682385521
spec:
  type: LoadBalancer
  selector:
    app: mytcsapp1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000