apiVersion: v1
kind: Service
metadata:
  name: firstapp
  namespace: namespace-workflow-1719845924644
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: firstapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000